
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import controller.ProjectController;
import java.sql.Connection;
import java.util.List;
import model.Project;
import util.ConnectionFactory;

public class App {

//    public static void main(String[] args) {
        
//        Connection c = ConnectionFactory.getConnection();
//        
//        ConnectionFactory.closeConnection(c);
    
    
        public static void main(String[] args) {
        //TODO  code  application logic here
        
//            System.out.println("Hello World");
        
//        ProjectController projectController = new ProjectController();
//        
//        Project project = new Project();
//        project.setName("Projeto teste");
//        project.setDescription("description");
//        System.out.println(project);
//        projectController.save(project);
        
//        project.setName("Novo nome do projeto");
//        projectController.update(project);
//        
//        List<Project> projects = projectController.getAll();
//        System.out.println("Total de projetos" + projects.size());
        
             
    }
}
